"""empty message

Revision ID: 03f1a1094f22
Revises: 0e2704e8f023
Create Date: 2018-03-05 18:58:33.448505

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '03f1a1094f22'
down_revision = '0e2704e8f023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
