"""empty message

Revision ID: 406d0c5c6ceb
Revises: d637f5446fa9
Create Date: 2018-04-08 21:11:17.704742

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '406d0c5c6ceb'
down_revision = 'd637f5446fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instagram_queuer', sa.Column('date_posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instagram_queuer', 'date_posted')
    # ### end Alembic commands ###
