"""empty message

Revision ID: 4c75c78e3945
Revises: cca57802e945
Create Date: 2018-03-29 16:32:11.273831

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4c75c78e3945'
down_revision = 'cca57802e945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_queuer',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('content', sa.Text(), nullable=True),
                    sa.Column('image_url', sa.Text(), nullable=False),
                    sa.Column('date_queued', sa.DateTime(), nullable=True),
                    sa.Column('user_email', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instagram_queuer')
    # ### end Alembic commands ###
