"""empty message

Revision ID: 6162a3fafdd0
Revises: 03f1a1094f22
Create Date: 2018-03-09 19:50:54.570027

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6162a3fafdd0'
down_revision = '03f1a1094f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credentials')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('facebook_', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('user_email', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['user_email'], ['users.email'], name='credentials_user_email_fkey'),
                    sa.PrimaryKeyConstraint('id', name='credentials_pkey')
                    )
    # ### end Alembic commands ###
