"""empty message

Revision ID: 65c2a261983c
Revises: a6970d2d9810
Create Date: 2018-02-26 19:12:10.072559

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '65c2a261983c'
down_revision = 'a6970d2d9810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date_posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'date_posted')
    # ### end Alembic commands ###
