"""empty message

Revision ID: a582a289fe37
Revises: cbf565173bf3
Create Date: 2018-02-26 18:21:27.907732

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a582a289fe37'
down_revision = 'cbf565173bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('social_network', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'social_network')
    # ### end Alembic commands ###
