"""empty message

Revision ID: cbf565173bf3
Revises: 
Create Date: 2018-02-26 17:37:11.893229

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cbf565173bf3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('email', sa.String(length=80), nullable=False),
                    sa.Column('password', sa.String(length=80), nullable=True),
                    sa.Column('name', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('email')
                    )
    op.create_table('post',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.Text(), nullable=True),
                    sa.Column('content', sa.Text(), nullable=True),
                    sa.Column('user_email', sa.String(length=80), nullable=True),
                    sa.ForeignKeyConstraint(['user_email'], ['user.email'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###
