"""empty message

Revision ID: cca57802e945
Revises: 6162a3fafdd0
Create Date: 2018-03-13 18:55:20.806286

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cca57802e945'
down_revision = '6162a3fafdd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'link')
    # ### end Alembic commands ###
