"""empty message

Revision ID: d637f5446fa9
Revises: 4c75c78e3945
Create Date: 2018-03-31 18:42:08.315028

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd637f5446fa9'
down_revision = '4c75c78e3945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instagram_queuer', sa.Column('status', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instagram_queuer', 'status')
    # ### end Alembic commands ###
